server:
  port: 8090

# Native is being used for local Repository
#spring:#  profiles:#    active: native

spring:  cloud:    config:      server:        git:          uri: https://github.com/rajit89/spring-config-store
          search-paths:          - '*service'
          #username: 
          #password: 
